# Generated by Django 5.2.5 on 2026-02-26 17:23

from django.db import migrations


RESTORATION_TYPES = [
    {"name": "Crown", "requires_tooth_number": True},
    {"name": "Crown w/Access Hole", "requires_tooth_number": True},
    {"name": "Coping", "requires_tooth_number": True},
    {"name": "Screw-retained Crown", "requires_tooth_number": True},
    {"name": "Bridge", "requires_tooth_number": True},
    {"name": "Custom Abutment", "requires_tooth_number": True},
    {"name": "Bar", "requires_tooth_number": False},
    {"name": "3D Printed Model", "requires_tooth_number": False},
]


def seed_restoration_types(apps, schema_editor):
    RestorationType = apps.get_model("restorations", "RestorationType")
    for rt in RESTORATION_TYPES:
        RestorationType.objects.get_or_create(
            name=rt["name"],
            defaults={"requires_tooth_number": rt["requires_tooth_number"]},
        )


def unseed_restoration_types(apps, schema_editor):
    RestorationType = apps.get_model("restorations", "RestorationType")
    RestorationType.objects.filter(name__in=[rt["name"] for rt in RESTORATION_TYPES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("restorations", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_restoration_types, unseed_restoration_types),
    ]
