# Generated by Django 5.2.5 on 2026-02-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorations', '0002_seed_restoration_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='restoration_types',
            field=models.ManyToManyField(blank=True, related_name='materials', to='restorations.restorationtype'),
        ),
        migrations.AddField(
            model_name='product',
            name='restoration_types',
            field=models.ManyToManyField(blank=True, related_name='products', to='restorations.restorationtype'),
        ),
    ]
