# Generated by Django 5.2.5 on 2026-02-26 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorations', '0003_material_restoration_types_product_restoration_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='restoration_types',
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='restorations.material'),
            preserve_default=False,
        ),
    ]
