# Generated by Django 5.2.5 on 2026-02-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorations', '0004_remove_product_restoration_types_product_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='has_products',
            field=models.BooleanField(default=False),
        ),
    ]
