# Generated by Django 5.2.5 on 2026-02-26 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorations', '0005_material_has_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('group', models.PositiveSmallIntegerField(choices=[(1, 'Other'), (2, 'VITA Classical A1-D4'), (3, 'VITA 3D-MASTER'), (4, 'Ivoclar Bleach')])),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shade',
                'verbose_name_plural': 'Shades',
                'ordering': ['group', 'sort_order'],
            },
        ),
        migrations.AddField(
            model_name='restorationtype',
            name='requires_shade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restoration',
            name='shade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='restorations.shade'),
        ),
    ]
