# Generated by Django 5.2.5 on 2026-02-26 18:09

from django.db import migrations

SHADES = [
    # Other
    {"pk": 33, "name": "Custom (Note)",    "group": 1, "sort_order": 1},
    {"pk": 38, "name": "White (Zirconia)", "group": 1, "sort_order": 2},
    # VITA Classical A1-D4
    {"pk": 1,  "name": "A1",   "group": 2, "sort_order": 1},
    {"pk": 2,  "name": "A2",   "group": 2, "sort_order": 2},
    {"pk": 3,  "name": "A3",   "group": 2, "sort_order": 3},
    {"pk": 4,  "name": "A3.5", "group": 2, "sort_order": 4},
    {"pk": 5,  "name": "A4",   "group": 2, "sort_order": 5},
    {"pk": 6,  "name": "B1",   "group": 2, "sort_order": 6},
    {"pk": 7,  "name": "B2",   "group": 2, "sort_order": 7},
    {"pk": 8,  "name": "B3",   "group": 2, "sort_order": 8},
    {"pk": 9,  "name": "B4",   "group": 2, "sort_order": 9},
    {"pk": 10, "name": "C1",   "group": 2, "sort_order": 10},
    {"pk": 11, "name": "C2",   "group": 2, "sort_order": 11},
    {"pk": 12, "name": "C3",   "group": 2, "sort_order": 12},
    {"pk": 13, "name": "C4",   "group": 2, "sort_order": 13},
    {"pk": 14, "name": "D2",   "group": 2, "sort_order": 14},
    {"pk": 15, "name": "D3",   "group": 2, "sort_order": 15},
    {"pk": 16, "name": "D4",   "group": 2, "sort_order": 16},
    # VITA 3D-MASTER
    {"pk": 17, "name": "0M1",          "group": 3, "sort_order": 1},
    {"pk": 18, "name": "0M2",          "group": 3, "sort_order": 2},
    {"pk": 19, "name": "0M3",          "group": 3, "sort_order": 3},
    {"pk": 20, "name": "1M1",          "group": 3, "sort_order": 4},
    {"pk": 21, "name": "1M2",          "group": 3, "sort_order": 5},
    {"pk": 25, "name": "2L1.5",        "group": 3, "sort_order": 6},
    {"pk": 39, "name": "2L2.5 -> A2",  "group": 3, "sort_order": 7},
    {"pk": 23, "name": "2M1",          "group": 3, "sort_order": 8},
    {"pk": 24, "name": "2M2",          "group": 3, "sort_order": 9},
    {"pk": 40, "name": "2M3 -> A3",    "group": 3, "sort_order": 10},
    {"pk": 22, "name": "2R1.5",        "group": 3, "sort_order": 11},
    {"pk": 41, "name": "2R2.5 -> A3",  "group": 3, "sort_order": 12},
    {"pk": 26, "name": "3L1.5",        "group": 3, "sort_order": 13},
    {"pk": 42, "name": "3L2.5 -> B3",  "group": 3, "sort_order": 14},
    {"pk": 27, "name": "3M1",          "group": 3, "sort_order": 15},
    {"pk": 28, "name": "3M2",          "group": 3, "sort_order": 16},
    {"pk": 43, "name": "3M3 -> A3.5",  "group": 3, "sort_order": 17},
    {"pk": 29, "name": "3R1.5",        "group": 3, "sort_order": 18},
    {"pk": 44, "name": "3R2.5 -> A3",  "group": 3, "sort_order": 19},
    {"pk": 45, "name": "4L1.5 -> C3",  "group": 3, "sort_order": 20},
    {"pk": 46, "name": "4L2.5 -> A3.5","group": 3, "sort_order": 21},
    {"pk": 30, "name": "4M1",          "group": 3, "sort_order": 22},
    {"pk": 31, "name": "4M2",          "group": 3, "sort_order": 23},
    {"pk": 47, "name": "4M3 -> B4",    "group": 3, "sort_order": 24},
    {"pk": 48, "name": "4R1.5 -> D3",  "group": 3, "sort_order": 25},
    {"pk": 49, "name": "4R2.5 -> A4",  "group": 3, "sort_order": 26},
    {"pk": 32, "name": "5M1",          "group": 3, "sort_order": 27},
    {"pk": 50, "name": "5M2 -> A4",    "group": 3, "sort_order": 28},
    {"pk": 51, "name": "5M3 -> A4",    "group": 3, "sort_order": 29},
    # Ivoclar Bleach
    {"pk": 34, "name": "BL1", "group": 4, "sort_order": 1},
    {"pk": 35, "name": "BL2", "group": 4, "sort_order": 2},
    {"pk": 36, "name": "BL3", "group": 4, "sort_order": 3},
    {"pk": 37, "name": "BL4", "group": 4, "sort_order": 4},
]


def seed_shades(apps, schema_editor):
    Shade = apps.get_model("restorations", "Shade")
    for s in SHADES:
        Shade.objects.get_or_create(pk=s["pk"], defaults={
            "name": s["name"],
            "group": s["group"],
            "sort_order": s["sort_order"],
        })


def unseed_shades(apps, schema_editor):
    Shade = apps.get_model("restorations", "Shade")
    Shade.objects.filter(pk__in=[s["pk"] for s in SHADES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("restorations", "0006_shade_restorationtype_requires_shade_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_shades, unseed_shades),
    ]
