# Generated by Django 5.2.5 on 2026-02-27 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorations', '0007_seed_shades'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplantSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Implant Size',
                'verbose_name_plural': 'Implant Sizes',
                'ordering': ['implant_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImplantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Implant Type',
                'verbose_name_plural': 'Implant Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TiBaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ti-Base Type',
                'verbose_name_plural': 'Ti-Base Types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='restoration',
            name='add_blocker',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restoration',
            name='arches',
            field=models.CharField(blank=True, choices=[('both', 'Both'), ('upper', 'Upper'), ('lower', 'Lower')], max_length=10),
        ),
        migrations.AddField(
            model_name='restoration',
            name='assembled_bonded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restoration',
            name='bar_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='restoration',
            name='design_service',
            field=models.CharField(blank=True, choices=[('mill_only', 'Mill Only'), ('design_and_mill', 'Design & Mill')], max_length=20),
        ),
        migrations.AddField(
            model_name='restoration',
            name='extra_separate_dies',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restoration',
            name='include_tibase',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restoration',
            name='is_screw_retained',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restoration',
            name='model_type',
            field=models.CharField(blank=True, choices=[('removable_dies', 'Removable Dies'), ('solid', 'Solid'), ('implant', 'Implant')], max_length=20),
        ),
        migrations.AddField(
            model_name='restoration',
            name='model_unit_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='restoration',
            name='number_of_units',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restoration',
            name='size',
            field=models.CharField(blank=True, choices=[('quad', 'Quad'), ('full', 'Full'), ('check', 'Check')], max_length=10),
        ),
        migrations.AddField(
            model_name='restoration',
            name='stain_and_glaze',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restoration',
            name='vertex_articulator',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restorationtype',
            name='extra_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='restoration',
            name='implant_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='restorations.implantsize'),
        ),
        migrations.AddField(
            model_name='implantsize',
            name='implant_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='restorations.implanttype'),
        ),
        migrations.AddField(
            model_name='restoration',
            name='implant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='restorations.implanttype'),
        ),
        migrations.AddField(
            model_name='restoration',
            name='tibase_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='restorations.tibasetype'),
        ),
        migrations.AlterUniqueTogether(
            name='implantsize',
            unique_together={('implant_type', 'name')},
        ),
    ]
