# Generated by Django 5.2.5 on 2026-02-27 15:29

from django.db import migrations

# Map restoration type names to their default extra_fields
SEED_DATA = {
    "Crown": [
        "add_blocker", "stain_and_glaze", "design_service",
    ],
    "Crown w/Access Hole": [
        "add_blocker", "stain_and_glaze", "design_service",
    ],
    "Coping": [
        "add_blocker", "design_service",
    ],
    "Screw-retained Crown": [
        "add_blocker", "include_tibase", "assembled_bonded",
        "stain_and_glaze", "design_service",
        "implant_type", "implant_size", "tibase_type",
    ],
    "Bridge": [
        "add_blocker", "stain_and_glaze", "design_service",
        "number_of_units", "is_screw_retained",
    ],
    "Bar": [
        "bar_details",
    ],
    "3D Printed Model": [
        "design_service", "model_type", "arches", "size",
        "extra_separate_dies", "vertex_articulator", "model_unit_details",
    ],
}


def seed_extra_fields(apps, schema_editor):
    RestorationType = apps.get_model("restorations", "RestorationType")
    for name, fields in SEED_DATA.items():
        RestorationType.objects.filter(name=name).update(extra_fields=fields)


def unseed_extra_fields(apps, schema_editor):
    RestorationType = apps.get_model("restorations", "RestorationType")
    RestorationType.objects.all().update(extra_fields=[])


class Migration(migrations.Migration):

    dependencies = [
        ('restorations', '0008_implantsize_implanttype_tibasetype_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_extra_fields, unseed_extra_fields),
    ]
