# Generated by Django 5.2.5 on 2026-02-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorations', '0009_seed_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='restoration',
            name='gold_anodizing',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
