# Generated by Django 5.2.5 on 2026-02-27

from django.db import migrations


def seed_custom_abutment(apps, schema_editor):
    RestorationType = apps.get_model("restorations", "RestorationType")
    RestorationType.objects.filter(name="Custom Abutment").update(
        extra_fields=["gold_anodizing", "design_service", "implant_type", "implant_size"]
    )


def unseed_custom_abutment(apps, schema_editor):
    RestorationType = apps.get_model("restorations", "RestorationType")
    RestorationType.objects.filter(name="Custom Abutment").update(extra_fields=[])


class Migration(migrations.Migration):

    dependencies = [
        ('restorations', '0010_restoration_gold_anodizing'),
    ]

    operations = [
        migrations.RunPython(seed_custom_abutment, unseed_custom_abutment),
    ]
