# Generated by Django 5.2.5 on 2026-02-27 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorations', '0011_seed_custom_abutment_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='restoration',
            name='case_note',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='RestorationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='restorations/%Y/%m/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('restoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='restorations.restoration')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
